/*
 * Copyright (C) 2019 Pablo Ugalde Trejos
 * UNIVERSIDAD ESTATAL A DISTANCIA
 * 00824 Programacion Intermedia
 */
package tarjetaseguridadbancaria;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pablo Ugalde Trejos
 */
//jform principal 
public class Vista extends javax.swing.JFrame {
    boolean valido = false; //variable para validar el formulario de persona
    int cantidadIntentos =0; //variable para la cantidad de intentos
    //variable para el color rojo de la prueba invalida
    Border borderInvalido = BorderFactory.createLineBorder(Color.red);
    //variable para el color rojo de la prueba valida
    Border borderValido = BorderFactory.createLineBorder(Color.BLUE);
    //arreglo principal para el objeto persona
    ArrayList<Persona> listaPersona = new ArrayList<Persona>();

    public Vista() {
        initComponents(); 
        jTablePersona.setDefaultEditor(Object.class, null);
        jTableTarjeta.setDefaultEditor(Object.class, null);
        jTableTarjeta.setAlignmentX(JLabel.CENTER);
        jTableTarjeta.setAlignmentY(JLabel.CENTER);
        formPersonaValidar();//llamado al proceso para marcar los campos como requeridos
        
        //configuracion de la fecha para el campo fechanacimiento
        Date cdate = new Date();
        Calendar cal = Calendar.getInstance();
        cal.setTime(cdate);
        cal.add(Calendar.YEAR, -20);
        dpFechaNacimiento.setDate(cal.getTime());
               
        //Agregamos los numeros de las filas a la tabla 
        DefaultTableModel modeloHHeader=(DefaultTableModel) jTableHHeader.getModel();
        modeloHHeader.addRow(new Object[]{"1"});
        modeloHHeader.addRow(new Object[]{"2"});
        modeloHHeader.addRow(new Object[]{"3"});
        modeloHHeader.addRow(new Object[]{"4"});
        modeloHHeader.addRow(new Object[]{"5"});
        modeloHHeader.addRow(new Object[]{"6"});
        modeloHHeader.addRow(new Object[]{"7"});
        modeloHHeader.addRow(new Object[]{"8"});
        panelProbar.setVisible(false);
    }

    //metodo para marcar los campos como requeridos
    //cambia el color del borde si estan vacios
    private void formPersonaValidar(){
        if(txtIdentificacion.getText().trim().isEmpty())
        {txtIdentificacion.setBorder(borderInvalido);valido = false;}
        else
        {txtIdentificacion.setBorder(borderValido);valido = true;}

        if(txtNombre.getText().trim().isEmpty())
        {txtNombre.setBorder(borderInvalido);valido = false;}
        else
        {txtNombre.setBorder(borderValido);valido = true;}
        
        if(txtApellido.getText().trim().isEmpty())
        {txtApellido.setBorder(borderInvalido);valido = false;}
        else
        {txtApellido.setBorder(borderValido);valido = true;}
        btnAgregar.setEnabled(valido);
    }

    //metodo para obtener tres campos aleatorios de la tarjeta de seguridad
    private void CrearIntento() {
        //variable con el indice del cliente
        int indiceCliente = jTableCliente.getSelectedRow();
        //obtener el objeto en el arreglo lista 
        Persona persona = listaPersona.get(indiceCliente);
        //obtener el objeto correspondiente a cliente
        Cliente cliente = persona.getCliente();
        //metodo para generar los tres campos aleatorios de la tarjeta de seguridad
        cliente.setTarjetaCelda();
        //se asigna el valor de cada campo aleatorio
        labCoor1.setText(cliente.getTarjetaCelda(0));
        txtCoor1.setText("");
        txtCoor1.setForeground(Color.BLACK);
        labCoor2.setText(cliente.getTarjetaCelda(2));
        txtCoor2.setText("");
        txtCoor2.setForeground(Color.BLACK);
        labCoor3.setText(cliente.getTarjetaCelda(4));
        txtCoor3.setText("");
        txtCoor3.setForeground(Color.BLACK);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbGroupSexo = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtIdentificacion = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        rbFemenino = new javax.swing.JRadioButton();
        rbMasculino = new javax.swing.JRadioButton();
        dpFechaNacimiento = new org.jdesktop.swingx.JXDatePicker();
        btnAgregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePersona = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableTarjeta = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableHHeader = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableCliente = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnGenerar = new javax.swing.JButton();
        panelProbar = new javax.swing.JPanel();
        labCoor1 = new javax.swing.JLabel();
        txtCoor1 = new javax.swing.JTextField();
        labCoor2 = new javax.swing.JLabel();
        txtCoor2 = new javax.swing.JTextField();
        labCoor3 = new javax.swing.JLabel();
        txtCoor3 = new javax.swing.JTextField();
        btnProbar = new javax.swing.JButton();
        lbIntentos = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableIntentos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Identificacion");

        jLabel2.setText("Nombre");

        jLabel3.setText("Apellido");

        jLabel4.setText("Sexo");

        jLabel5.setText("Fecha Nacimiento");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        txtIdentificacion.setColumns(10);
        txtIdentificacion.setName("txtIdentificacion"); // NOI18N
        txtIdentificacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIdentificacionKeyReleased(evt);
            }
        });

        txtNombre.setColumns(10);
        txtNombre.setName("txtNombre"); // NOI18N
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreKeyReleased(evt);
            }
        });

        txtApellido.setColumns(10);
        txtApellido.setName("txtApellido"); // NOI18N
        txtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtApellidoKeyReleased(evt);
            }
        });

        rbGroupSexo.add(rbFemenino);
        rbFemenino.setSelected(true);
        rbFemenino.setText("F");
        rbFemenino.setName("rbFemenino"); // NOI18N

        rbGroupSexo.add(rbMasculino);
        rbMasculino.setText("M");

        btnAgregar.setText("Agregar");
        btnAgregar.setEnabled(false);
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar)
                    .addComponent(dpFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(rbFemenino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbMasculino))
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbFemenino)
                    .addComponent(rbMasculino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dpFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTablePersona.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificacion", "Nombre", "Apellido", "Sexo", "Fec Nac", "Edad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablePersona.setColumnSelectionAllowed(true);
        jTablePersona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePersonaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePersona);
        jTablePersona.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jTablePersona.getColumnModel().getColumnCount() > 0) {
            jTablePersona.getColumnModel().getColumn(0).setResizable(false);
            jTablePersona.getColumnModel().getColumn(3).setHeaderValue("Sexo");
            jTablePersona.getColumnModel().getColumn(4).setResizable(false);
            jTablePersona.getColumnModel().getColumn(4).setHeaderValue("Fec Nac");
            jTablePersona.getColumnModel().getColumn(5).setResizable(false);
            jTablePersona.getColumnModel().getColumn(5).setHeaderValue("Edad");
        }

        jTableTarjeta.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTableTarjeta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "A", "B", "C", "D", "E", "F", "G", "H"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableTarjeta.setMaximumSize(new java.awt.Dimension(300, 128));
        jTableTarjeta.setRowHeight(19);
        jTableTarjeta.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTableTarjeta);
        if (jTableTarjeta.getColumnModel().getColumnCount() > 0) {
            jTableTarjeta.getColumnModel().getColumn(0).setResizable(false);
            jTableTarjeta.getColumnModel().getColumn(1).setResizable(false);
            jTableTarjeta.getColumnModel().getColumn(1).setHeaderValue("B");
            jTableTarjeta.getColumnModel().getColumn(2).setResizable(false);
            jTableTarjeta.getColumnModel().getColumn(2).setHeaderValue("C");
            jTableTarjeta.getColumnModel().getColumn(3).setResizable(false);
            jTableTarjeta.getColumnModel().getColumn(3).setHeaderValue("D");
            jTableTarjeta.getColumnModel().getColumn(4).setHeaderValue("E");
            jTableTarjeta.getColumnModel().getColumn(5).setResizable(false);
            jTableTarjeta.getColumnModel().getColumn(5).setHeaderValue("F");
            jTableTarjeta.getColumnModel().getColumn(6).setResizable(false);
            jTableTarjeta.getColumnModel().getColumn(6).setHeaderValue("G");
            jTableTarjeta.getColumnModel().getColumn(7).setResizable(false);
            jTableTarjeta.getColumnModel().getColumn(7).setHeaderValue("H");
        }

        jTableHHeader.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTableHHeader.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "  "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableHHeader.setMaximumSize(new java.awt.Dimension(300, 128));
        jTableHHeader.setRowHeight(19);
        jTableHHeader.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jTableHHeader);
        if (jTableHHeader.getColumnModel().getColumnCount() > 0) {
            jTableHHeader.getColumnModel().getColumn(0).setResizable(false);
        }

        jLabel9.setText("Seleccione una persona para ver la Tarjeta de Seguridad:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Personas", jPanel1);

        jTableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificacion", "Nombre", "Apellido"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableClienteMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTableCliente);
        jTableCliente.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jTableCliente.getColumnModel().getColumnCount() > 0) {
            jTableCliente.getColumnModel().getColumn(0).setResizable(false);
        }

        jLabel6.setText("1. Seleccione un cliente:");

        jLabel7.setText("2. Genere una nueva combinacion:");

        btnGenerar.setText("Generar");
        btnGenerar.setEnabled(false);
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        labCoor1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labCoor1.setForeground(new java.awt.Color(0, 153, 153));

        txtCoor1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtCoor1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCoor1KeyTyped(evt);
            }
        });

        labCoor2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labCoor2.setForeground(new java.awt.Color(0, 153, 153));

        txtCoor2.setColumns(2);
        txtCoor2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtCoor2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCoor2KeyTyped(evt);
            }
        });

        labCoor3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labCoor3.setForeground(new java.awt.Color(0, 153, 153));

        txtCoor3.setColumns(2);
        txtCoor3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtCoor3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCoor3KeyTyped(evt);
            }
        });

        btnProbar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnProbar.setText("Probar");
        btnProbar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProbarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelProbarLayout = new javax.swing.GroupLayout(panelProbar);
        panelProbar.setLayout(panelProbarLayout);
        panelProbarLayout.setHorizontalGroup(
            panelProbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProbarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labCoor1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCoor1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labCoor2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCoor2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labCoor3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCoor3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProbar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelProbarLayout.setVerticalGroup(
            panelProbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProbarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelProbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelProbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labCoor1)
                        .addComponent(txtCoor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labCoor2)
                        .addComponent(txtCoor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labCoor3)
                        .addComponent(txtCoor3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnProbar)))
        );

        lbIntentos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbIntentos.setForeground(new java.awt.Color(255, 51, 255));
        lbIntentos.setText("Tiene 3 de 3 intentos.");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGenerar))
                    .addComponent(panelProbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbIntentos, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(btnGenerar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelProbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbIntentos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Simulacion", jPanel4);

        jTableIntentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificacion", "Nombre Completo", "Intento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableIntentos.getTableHeader().setReorderingAllowed(false);
        jScrollPane5.setViewportView(jTableIntentos);
        if (jTableIntentos.getColumnModel().getColumnCount() > 0) {
            jTableIntentos.getColumnModel().getColumn(0).setResizable(false);
            jTableIntentos.getColumnModel().getColumn(1).setResizable(false);
            jTableIntentos.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(168, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(152, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Historial", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //metodo del boton agregar
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        //creamos un objeto nuevo de la clase persona
        //agregamos los datos ingresados y validados por el usuario
        Persona persona=new Persona();
        persona.setIdentificacion(Integer.parseInt(txtIdentificacion.getText()));
        persona.setNombre(txtNombre.getText());
        persona.setApellido(txtApellido.getText());
        if (rbFemenino.isSelected()){persona.setSexo('F');}else{persona.setSexo('M');}
        persona.setFechanacimiento(dpFechaNacimiento.getDate());
        //calculamos la edad con respecto a la fecha de nacimiento
        persona.setEdadDiff(dpFechaNacimiento.getDate());
        
        //crear el modelo de la tabla de datos para la clase persona
        DefaultTableModel modeloPersona=(DefaultTableModel) jTablePersona.getModel();
        //se agrega la linea con los datos a la tabla
        modeloPersona.addRow(new Object[]{
            persona.getIdentificacion(),
            persona.getNombre(),
            persona.getApellido(),
            persona.getSexo(),
            persona.getFechanacimientoStrFormat(),
            persona.getEdad()
        });
        
        //crear un objeto cliente de la clase cliente
        //con los parametros del rango de numeros aleatorios para 
        //la tarjeta de seguridad
        Cliente cliente=new Cliente(10,99);
        //asignamos la identificacion al numero de cliente
        cliente.setNumerocliente(Integer.parseInt(txtIdentificacion.getText()));
        //creamos el arreglo bidimensional para la tarjeta de seguridad
        cliente.setNumerotarjeta();
        //llenamos el arreglo de la tarjeta de seguridad
        cliente.LlenaTarjeta();
        //agregamos el cliente a persona
        persona.setCliente(cliente);

        //crear el modelo de la tabla de datos para la clase cliente
        DefaultTableModel modeloCliente=(DefaultTableModel) jTableCliente.getModel();
        //se agrega la linea con los datos a la tabla
        modeloCliente.addRow(new Object[]{
            persona.getIdentificacion(),
            persona.getNombre(),
            persona.getApellido()
        });
        
        //agregamos el objeto persona a la lista personas
        listaPersona.add(persona);
        //limpiamos los campos
        txtIdentificacion.setText("");
        txtIdentificacion.requestFocus();
        txtNombre.setText("");
        txtApellido.setText("");
        
        //llamado al proceso para marcar los campos como requeridos
        formPersonaValidar();
        panelProbar.setVisible(false);
    }//GEN-LAST:event_btnAgregarActionPerformed

    //metodo para seleccion de fila en la tabla persona
    //carga la tarjeta de seguridad respectiva en la tabla
    private void jTablePersonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePersonaMouseClicked
        //variable con el indice del persona
        int indicePersona = jTablePersona.getSelectedRow();
        //crear el modelo de la tabla de datos para la clase tarjeta
        DefaultTableModel modeloTarjeta=(DefaultTableModel) jTableTarjeta.getModel();
        //removemos todos los datos existentes en la tabla
        modeloTarjeta.getDataVector().removeAllElements();
        modeloTarjeta.fireTableDataChanged();
        
        //buscamos el objeto persona en la lista
        Persona persona = listaPersona.get(indicePersona);
        //buscamos el objeto cliente del objeto persona
        Cliente cliente = persona.getCliente();
        
        //recorremos la tarjeta del objeto cliente
        //cargamos linea por linea en la tabla
        for (int i = 0; i < cliente.getNumerotarjeta().length; i++) {
            String[] row = new String[cliente.getNumerotarjeta()[i].length];
            for (int j = 0; j < cliente.getNumerotarjeta()[i].length; j++) {
                row[j]= String.valueOf(cliente.getNumerotarjeta()[i][j]);
            }
            modeloTarjeta.addRow(row);
        }
    }//GEN-LAST:event_jTablePersonaMouseClicked

    //metodo para seleccion de fila en la tabla cliente
    //habilita los elementos necesarios para realizar el simulacro
    private void jTableClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableClienteMouseClicked
        try {
            panelProbar.setVisible(false);
            btnGenerar.setEnabled(true);
        } catch (Exception e) {
            panelProbar.setVisible(false);
            btnGenerar.setEnabled(false);
        }
    }//GEN-LAST:event_jTableClienteMouseClicked

    //metodo del boton generar 
    //habilita los elementos necesarios
    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        panelProbar.setVisible(true);
        cantidadIntentos=0;
        btnGenerar.setEnabled(false);
        btnProbar.setEnabled(true);
        lbIntentos.setText("Tiene 3 de 3 intentos.");
        //llamado al metodo para obtener tres campos aleatorios de la tarjeta de seguridad
        CrearIntento();
    }//GEN-LAST:event_btnGenerarActionPerformed

    //metodo del boton probar 
    private void btnProbarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProbarActionPerformed
        //aumentamos los intentos uno por uno
        cantidadIntentos=cantidadIntentos+1;
        lbIntentos.setText("Tiene "+ String.valueOf(3-cantidadIntentos) +" de 3 intentos.");
        
        //variable con el indice de cliente
        int indiceCliente = jTableCliente.getSelectedRow();       
        //buscamos el objeto persona en la lista
        Persona persona = listaPersona.get(indiceCliente);
        //buscamos el objeto cliente en el objeto persona
        Cliente cliente = persona.getCliente();
        String strIntento = "";

        //evaluamos los campos ingresados
        if (Integer.parseInt(txtCoor1.getText()) != Integer.parseInt(cliente.getTarjetaCelda(1))){
            strIntento = strIntento+labCoor1.getText()+" (x) - ";
            txtCoor1.setForeground(Color.red);
        } 
        else{
            strIntento = strIntento+labCoor1.getText()+" - ";
            txtCoor1.setForeground(Color.BLACK);
        }
        if (Integer.parseInt(txtCoor2.getText())!=Integer.parseInt(cliente.getTarjetaCelda(3))){
            strIntento = strIntento+labCoor2.getText()+" (x) - ";
            txtCoor2.setForeground(Color.red);
        } 
        else{
            strIntento = strIntento+labCoor2.getText()+" - ";
            txtCoor2.setForeground(Color.BLACK);
        }
        if (Integer.parseInt(txtCoor3.getText())!=Integer.parseInt(cliente.getTarjetaCelda(5))){
            strIntento = strIntento+labCoor3.getText()+" (x)";
            txtCoor3.setForeground(Color.red);
        } 
        else{
            strIntento = strIntento+labCoor3.getText();
            txtCoor3.setForeground(Color.BLACK);
        }
        //si el intento tiene errores lo agregamos a la tabla
        //de intentos fallidos
        if (strIntento.contains("(x)")) {
            DefaultTableModel modeloIntentos = (DefaultTableModel) jTableIntentos.getModel();
            modeloIntentos.addRow(new Object[]{
                persona.getIdentificacion(),
                persona.getNombre() + " " + persona.getApellido(),
                strIntento
            });
        }
        //evaluamos si ya supero la cantidad de intentos
        if (cantidadIntentos==3){
            cantidadIntentos=0;
            lbIntentos.setText("No tiene mas intentos, vuelva a Generar.");
            btnGenerar.setEnabled(true);
            btnProbar.setEnabled(false);
            panelProbar.setVisible(false);
        }
        else{
            //sino creamos otro intento
            CrearIntento();
        }
        
    }//GEN-LAST:event_btnProbarActionPerformed

    //metodo para validar la entrada de datos de Idenfiticacion 
    private void txtIdentificacionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdentificacionKeyReleased
        try {
            txtIdentificacion.setBorder(borderValido);
            //si el valor ingresado no es integer es una excepcion
            int i = Integer.parseInt(txtIdentificacion.getText());
            formPersonaValidar();
        } catch (NumberFormatException e) {
            txtIdentificacion.setBorder(borderInvalido);
            valido = false;
        }
    }//GEN-LAST:event_txtIdentificacionKeyReleased

    //metodo para validar la entrada de datos de nombre
    private void txtNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyReleased
        try {
            formPersonaValidar();
        } catch (Exception e) {
            txtIdentificacion.setBorder(borderInvalido);
            valido = false;
        }
    }//GEN-LAST:event_txtNombreKeyReleased

    //metodo para validar la entrada de datos de Apellido 
    private void txtApellidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyReleased
        try {
            formPersonaValidar();
        } catch (Exception e) {
            txtApellido.setBorder(borderInvalido);
            valido = false;
        }
    }//GEN-LAST:event_txtApellidoKeyReleased

    //metodo para validar la entrada de datos
    //del campo 1 de la prueba de simulacro
    //sino es integer suena un beep
    private void txtCoor1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCoor1KeyTyped
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9') || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE) ) ) {
            getToolkit().beep();
            evt.consume();
        }
        else{
            if (txtCoor1.getText().length()+1 > 2) {
                getToolkit().beep();
                evt.consume();
            }
        }
    }//GEN-LAST:event_txtCoor1KeyTyped

    //metodo para validar la entrada de datos
    //del campo 2 de la prueba de simulacro
    //sino es integer suena un beep
    private void txtCoor2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCoor2KeyTyped
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9') || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE) ) ) {
            getToolkit().beep();
            evt.consume();
        }
        else{
            if (txtCoor2.getText().length()+1 > 2) {
                getToolkit().beep();
                evt.consume();
            }
        }
    }//GEN-LAST:event_txtCoor2KeyTyped

    //metodo para validar la entrada de datos
    //del campo 3 de la prueba de simulacro
    //sino es integer suena un beep
    private void txtCoor3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCoor3KeyTyped
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9') || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE) ) ) {
            getToolkit().beep();
            evt.consume();
        }
        else{
            if (txtCoor3.getText().length()+1 > 2) {
                getToolkit().beep();
                evt.consume();
            }
        }
    }//GEN-LAST:event_txtCoor3KeyTyped

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btnProbar;
    private org.jdesktop.swingx.JXDatePicker dpFechaNacimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableCliente;
    private javax.swing.JTable jTableHHeader;
    private javax.swing.JTable jTableIntentos;
    private javax.swing.JTable jTablePersona;
    private javax.swing.JTable jTableTarjeta;
    private javax.swing.JLabel labCoor1;
    private javax.swing.JLabel labCoor2;
    private javax.swing.JLabel labCoor3;
    private javax.swing.JLabel lbIntentos;
    private javax.swing.JPanel panelProbar;
    private javax.swing.JRadioButton rbFemenino;
    private javax.swing.ButtonGroup rbGroupSexo;
    private javax.swing.JRadioButton rbMasculino;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCoor1;
    private javax.swing.JTextField txtCoor2;
    private javax.swing.JTextField txtCoor3;
    private javax.swing.JTextField txtIdentificacion;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
